name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./api/ --tag leo999/web:${{ github.run_number }}
    - name: Push docker
      run: |
        docker login -u leo999 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push leo999/web:${{ github.run_number }}
